version: '3.8'

services:
  ultra-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ultra-bugbounty-scanner
    env_file:
      - .env
    
    # Mantiene la sesión interactiva viva
    tty: true
    
    volumes:
      - ./output:/app/output:rw
      - ./wordlists:/app/wordlists:ro
      
    dns:
      - 8.8.8.8
      - 1.1.1.1
      
    security_opt:
      - no-new-privileges:true
      
    restart: "no"

    networks:
      - scanner-network

networks:
  scanner-network:
    driver: bridge

